/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* model_expl_ode_fun:(i0[9],i1[6],i2[])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=-1.0000000000000000e-03;
  a1=arg[1]? arg[1][0] : 0;
  a2=(a0*a1);
  a3=-2.0000000000000000e-03;
  a4=1.0700000000000000e-01;
  a5=arg[0]? arg[0][3] : 0;
  a5=sin(a5);
  a5=(a4*a5);
  a5=(a3+a5);
  a6=casadi_sq(a5);
  a7=4.5999999999999999e-02;
  a8=arg[0]? arg[0][4] : 0;
  a8=sin(a8);
  a8=(a4*a8);
  a7=(a7+a8);
  a8=casadi_sq(a7);
  a6=(a6+a8);
  a6=sqrt(a6);
  a2=(a2/a6);
  a8=arg[1]? arg[1][2] : 0;
  a9=(a0*a8);
  a10=arg[0]? arg[0][5] : 0;
  a10=sin(a10);
  a10=(a4*a10);
  a3=(a3+a10);
  a10=casadi_sq(a3);
  a11=-4.5999999999999999e-02;
  a12=arg[0]? arg[0][6] : 0;
  a12=sin(a12);
  a12=(a4*a12);
  a12=(a11+a12);
  a13=casadi_sq(a12);
  a10=(a10+a13);
  a10=sqrt(a10);
  a9=(a9/a10);
  a13=(a2+a9);
  a14=arg[1]? arg[1][4] : 0;
  a15=(a0*a14);
  a16=8.4000000000000005e-02;
  a17=arg[0]? arg[0][7] : 0;
  a17=sin(a17);
  a17=(a4*a17);
  a16=(a16+a17);
  a17=casadi_sq(a16);
  a18=arg[0]? arg[0][8] : 0;
  a18=sin(a18);
  a4=(a4*a18);
  a11=(a11+a4);
  a4=casadi_sq(a11);
  a17=(a17+a4);
  a17=sqrt(a17);
  a15=(a15/a17);
  a13=(a13+a15);
  a4=2.9999999999999999e-01;
  a13=(a13/a4);
  if (res[0]!=0) res[0][1]=a13;
  a13=arg[1]? arg[1][1] : 0;
  a4=(a0*a13);
  a4=(a4/a6);
  a4=(a4*a5);
  a2=(a2*a7);
  a4=(a4-a2);
  a2=arg[1]? arg[1][3] : 0;
  a7=(a0*a2);
  a7=(a7/a10);
  a7=(a7*a3);
  a4=(a4+a7);
  a9=(a9*a12);
  a4=(a4-a9);
  a9=arg[1]? arg[1][5] : 0;
  a0=(a0*a9);
  a0=(a0/a17);
  a0=(a0*a16);
  a4=(a4+a0);
  a15=(a15*a11);
  a4=(a4-a15);
  a15=4.0000000000000001e-03;
  a4=(a4/a15);
  if (res[0]!=0) res[0][2]=a4;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a13;
  if (res[0]!=0) res[0][5]=a8;
  if (res[0]!=0) res[0][6]=a2;
  if (res[0]!=0) res[0][7]=a14;
  if (res[0]!=0) res[0][8]=a9;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real model_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
